name: ElTrader
main: com.elesia.eltrader.core.ElTraderManager
version: 0.0.1-ALPHA
author: Uicias
api-version: 1.14
description: Plugin qui permet de créer et gérer des traders (Villageois)
depend:
  - ElenoxCore
commands:
  eltrader:
    description: Permet des actions sur les traders de ce plugin